// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://txqfdscdlltohpkkznwa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4cWZkc2NkbGx0b2hwa2t6bndhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM5ODc1NzQsImV4cCI6MjA5OTU2MzU3NH0.a3oMZQ3yap3At2gJmGBYj-pXdQ9GHQX8teqDKyjXP58";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});